name: release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: (MMMM, DD, YYYY)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          release_name: ${{ steps.get_version.outputs.tag }}
          body: |
            ## ${{ steps.get_version.outputs.tag }} ${{ steps.current-time.outputs.formattedTime }}
          draft: false
          prerelease: false
