name: releasesdk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: (MMMM, DD, YYYY)
      - name: Set tag from project
        run: |
          exec .github/scripts/set-tag.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: $buildNumber
          release_name: $buildNumber
          body: |
            ## $buildNumber ${{ steps.current-time.outputs.formattedTime }}
          draft: false
          prerelease: false
